import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  DM_Mono,
  Cormorant_Garamond,
  JetBrains_Mono,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ToastProvider } from "@/hooks/useToast";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: "300",
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "---font-cormorand-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FYPOF - Find Your Peak of Fiction",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-mono", jetbrainsMono.variable)}>
      <body
        className={`${geistSans.variable} ${dmMono.variable} ${cormorantGaramond.variable} antialiased`}
      >
        {/* <Toaster
          position="top-right"
          closeButton
          toastOptions={{
            classNames: {
              toast: "animate-in fade-in slide-in-from-right-5 duration-300",
            },
          }}
        /> */}
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
